version: '3.8'

services:
  advent-bot:
    build: .
    container_name: advent-bot
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    env_file: .env
    volumes:
      - advent-bot-db-data:/app/data
    networks:
      - advent-network

networks:
  advent-network:
    driver: bridge

volumes:
  advent-bot-db-data:
